a1 = r"""
                     ..^....                     
                  ..}*@B#@@@;..                  
               .!@@@WkdddddaB@@n..               
            ..@@@*bddddddddddda@@@M..            
         .Q@@@*ddddddddddddddddddkB@@@_..        
      .{B@Bbdddddddddddddddddddddddddh@@@b..     
   .@@@@hdddddddddddddddddddddddddddddddh@@@@.   
   ,Wddddddddddddddddddddddddddddddddbbbdddd@<   
   !hddddddddddddddddddddddddddddddddm0bdddd@I   
   .kdddddddddddddddb@@@@@@*dddddddddbbbdddd@~   
   :hddddddddddddddd*@{...@@dddddddddddddddd@[   
   .hddddddddddddddd*C....@@dddddddddddddddd@[   
   .hdddddddddddddddo@@@..@@dddddddddddddddd@~   
   lkddddddddddddddddd@@..@@dddddddddddddddd@)   
   lkddddddddddddddddd@@..@@dddddddddddddddd@1   
   .hddddddddddddddddd@Z..@@dddddddddddddddd@]   
   .oddddddddddddddddd$@@@@#dddddddddddddddd@[   
   .*ddddddddddddddddddddddddddddddddddddddd@;   
   :@ddddddddddddddddddddddddddddddddddddddd@-   
   .@@@MhddddddddddddddddddddddddddddddddM@@@.   
     .n@@@Bodddddddddddddddddddddddddk*@@@..     
        ...@@$adddddddddddddddddddo@@a~..        
            .i@@$hbdddddddddddda@@@..            
               ./M@@addddddba$@@~.               
                  ..CB@Mk*@#n..                  
                     .."<i..                     
"""

a18 = r"""
                     ..^....                     
                  ..}*@B#@@@;..                  
               .!@@@WkdddddaB@@j..               
            ..@@@*bdddddddddddo@@@@..            
         .Q@@@*ddddddddddddddddddkB@@@_..        
      .{B@Bbdddddddddddddddddddddddddh@@@b..     
   .@@@@hdddddddddddddddddddddddddddddddh@@@@.   
   ,Wddddddddddddddddddddddddddddddddddddddd@<   
   !hddddddddddddddddddddddddddddddddddddddd@I   
   .kdddddddddddd#@@@@@@@@@@@@@@oddddddddddd@~   
   :hdddddddddddd@M...n@@h.....@@ddddddddddd@[   
   .hdddddddddddd@....x@t..@@b..@ddddddddddd@[   
   .hdddddddddddd@@@..h@@!.....@@hdddddddddd@^   
   lkddddddddddddd@@..k@@..;<..t@@dddddddddd@~   
   lkddddddddddddd@@..J@..n@@@..O@dddddddddd@i   
   .hddddddddddddd$@..)@@......@@Wdddddddddd@]   
   .oddddddddddddda@@@@@@@@@@@@@@ddddddddddd@[   
   .*ddddddddddddddddddddddddddddddddddddddd@I   
   :@ddwwwdddddddddddddddddddddddddddddddddd@i   
   .@@@*@wddddddddddddddddkddddddddddddddM@@@.   
     .n@@@Wodddddddddddddddddddddddddh*@@@..     
        ..`@@$adddddddddddddddddddo$@h!..        
            .i@@$hdddddddddddddh@@@..            
               .1@@@addddddba$@@(.               
                  ..CB@Mk*@#n..                  
                     .."<i..                     
"""
a2 = r"""
                     ..^....                     
                  ..}*@B#@@@;..                  
               .!@@@WkdddddaB@@X..               
            ..@@@*bdddddddddddaB@@@..            
         .Q@@@*ddddddddddddddddddbB@@@_..        
      .{B@Bbdddddddddddddddddddddddddh@@@b..     
   .@@@@hdddddddddddddddddddddddddddddddh@@@@.   
   ,Wddddddddddddddddddddddddddddddddddddddd@<   
   !hddddddddddddddddddddddddddddddddddddddd@I   
   .kddddddddddddddd@@@@@@@@Wddddddddddddddd@~   
   :hddddddddddddddd@......@@odddddddddddddd@[   
   .kddddddddddddddd@Jn@@}..@Mdddddddddddddd@[   
   lkdddddddddddddddW@@@@C..@Mdddddddddddddd@~   
   lkdddddddddddddddW@@@...@@hdddddddddddddd@[   
   'hddddddddddddddM@@...@@@@Wdddddddddddddd@[   
   .addddddddddddddM}.......,Wdddddddddddddd@[   
   .oddddddddddddddM@@@@@@@@@Wdddddddddddddd@[   
   .*dddddddddddddddddbbkkbddddddddddddddddd@;   
   :@ddddddddddddddddddddddddddddddddddddddd@-   
   .@@@MhdddddddddddddddddddddkddddddddddM@@@.   
     .n@@@Bodddddddddddddddddddddddddk*@@@..     
        ...@@$addddddddddddddddddd#@@pl..        
            .i@@$hbdddddddddddda@@@..            
               ./M@@addddddba$@@].               
                  ..CB@Mk*@#n..                  
                     .."<i..                                              
"""
a17 = r"""
                     ..^....                     
                  ..}*@B#@@@;..                  
               .1@@@WkdddddaB@@n..               
            ."@@@adddddddddddda@@@W..            
         .Q@@$oddddddddddddddddddk$@@@_..        
      .{B@Bbdddddddddddddddddddddddddh@@@b..     
   .@@@@hdddddddddddddddddddddddddddddddh@@@@.   
   ,Wddddddddddddddddddddddddddddddddddddddd@<   
   !hddddddddddddddddddddddddddddddddddddddd@I   
   .kdddddddddddd@@@@@@@@@@@@@@@@ddddddddddd@~   
   :hdddddddddddo@~...@@.......:@ddddddddddd@[   
   .hdddddddddddoZ....@@@@@@@..@@ddddddddddd@[   
   'hdddddddddddo@@@..@@#@@@..@@Wddddddddddd@^   
   !hddddddddddddd@@..@@@@@..@@@dddddddddddd@~   
   .hddddddddddddd@*..@@@@..@@@ddddddddddddd@i   
   .oddddddddddddd@n..@@@..i@@dddddddddddddd@]   
   .oddddddddddddd@@@@@#@@@@@bdddddddddddddd@[   
   .*ddddddddddddddddddddddddddddddddddddddd@;   
   :@ddddddddddddddddddddddddddddddddddddddd@-   
   .@@@MkddddddddddddddddddddddddddddddddM@@@.   
     .n@@@Wodddddddddddddddddddddddddk*@@@..     
        ..`@@Whdddddddddddddddddddo@@o~..        
            .~@@$hbdddddddddddda@@@'.            
               ./M@@addddddba$@@~.               
                  ..CB@Mk*@#n..                  
                     .."<i..                                   
"""
a16 = r"""
                     ..^....                     
                  ..}*@B#@@@;..                  
               ._@@@WkdddddaB@@J..               
            ..@@@oddddddddddddhB@@@..            
         .Q@@@*ddddddddddddddddddbB@@@_..        
      .{B@Bbdddddddddddddddddddddddddh@@@b..     
   .@@@@hdddddddddddddddddddddddddddddddh@@@@.   
   ,Wddddddddddddddddddddddddddddddddddddddd@<   
   !hddddddddddddddddddddddddddddddddddddddd@I   
   .kdddddddddddM@@@@@Wd$@@@@@@odddddddddddd@~   
   ,hddddddddddb@W...@@@@@....Yodddddddddddd@[   
   ,hddddddddddb@....@@@...@@@@@dddddddddddd@[   
   .kddddddddddb@@@..@@.......@@#ddddddddddd@^   
   lkdddddddddddd@@..@@..h@@*..@@@kddddddddd@~   
   !kdddddddddddd@@..@@..:@@@..@@@@ddddddddd@i   
   .adddddddddddd@@..B@@"...../...@ddddddddd@]   
   .*dddddddddddd#@@@@@@@@@@@@@@@@@ddddddddd@[   
   .*dddddddddddddddddddddbbbddddddddddddddd@;   
   :@ddwwwdddddddddddddddddddddddddddddddddd@-   
   .@@@*@wdddddddddddddddddddddddddddddddM@@@.   
     .n@@@Wodddddddddddddddddddddddddh*@@@..     
        ..`@@$adddddddddddddddddddaB@hI..        
            .i@@$hdddddddddddddh@@@^.            
               .1@@@addddddba$@@(.               
                  ..CB@Mk*@#n..                  
                     .."<i..                            
"""
a6 = r"""
                     ..^....                     
                  ..}*@B#@@@;..                  
               .!@@@WkdddddaB@@n..               
            ..@@@*bddddddddddda@@@M..            
         .Q@@@*ddddddddddddddddddkB@@@_..        
      .{B@Bbdddddddddddddddddddddddddh@@@b..     
   .@@@@hdddddddddddddddddddddddddddddddh@@@@.   
   ,Wddddddddddddddddddddddddddddddddddddddd@<   
   !hddddddddddddddddddddddddddddddddddddddd@I   
   .kdddddddddddddddM@@@@@@Bdddddddddddddddd@~   
   :hdddddddddddddh@@@.....Bdddddddddddddddd@[   
   .hddddddddddddd@@_..@@@@@dddddddddwdddddd@[   
   .addddddddddddh@(......@@@ddddddddddddddd@+   
   `addddddddddddh@...@@@..@@@oddddddddddddd@~   
   `addddddddddddh@<..@@@..@@@@ddddddddddddd@)   
   .oddddddddddddd@@b.....h...@ddddddddddddd@]   
   .*dddddddddddddb@@@@@@@@@@@@ddddddddddddd@[   
   .*dddddddddddddddddbbbddddddddddddddddddd@;   
   :@ddddddddddddddddddddddddddddddddddddddd@-   
   .@@@MhddddddddddddddddddddddddddddddddM@@@.   
     .n@@@Wodddddddddddddddddddddddddh*@@@..     
        ..`@@@adddddddddddddddddddaB@h!..        
            .;@@$hbddddddddddddhW@B^.            
               ./M@@addddddba$@@1.               
                  ..CB@Mk*@#n..                  
                     .."<i..                                            
"""
a15 = r"""
                     ..^....                     
                  ..}*@B#@@@;..                  
               .!@@@WkdddddaB@@n..               
            ..@@@*bddddddddddda@@@@..            
         .Q@@@*ddddddddddddddddddbB@@@_..        
      .{B@Bbdddddddddddddddddddddddddh@@@b..     
   .@@@@hdddddddddddddddddddddddddddddddh@@@@.   
   ,Wddddddddddddddddddddddddddddddddddddddd@<   
   !hddddddddddddddddddddddddddddddddddddddd@I   
   .kdddddddddddd#@@@@@@@@@@@@@@$ddddddddddd@~   
   :hdddddddddddd@M...r@@|......@ddddddddddd@[   
   .hdddddddddddd@....n@@..@@@@@@ddddddddddd@[   
   .hdddddddddddd@@@..b@@.....@@@ddddddddddd@^   
   !hddddddddddddd@@..m@@@@@@.."@ddddddddddd@~   
   .hddddddddddddd@@..Y@@@@@@...@ddddddddddd@i   
   .oddddddddddddd$@..[@......1@@ddddddddddd@]   
   .oddddddddddddda@@@@@@@@@@@@@kddddddddddd@[   
   .*ddddddddddddddddddddbkkbddddddddddddddd@;   
   :@ddddddddddddddddddddddddddddddddddddddd@-   
   .@@@MhddddddddddddddddddddddddddddddddM@@@.   
     .n@@@Wodddddddddddddddddddddddddh*@@@..     
        ..`@@$addddddddddddddddddd@@@@_..        
            .i@@$hbdddddddddddda@@@..            
               ./M@@addddddba$@@~.               
                  ..CB@Mk*@#n..                  
                     .."<i..                                              
"""
a7 = r"""
                     ..^....                     
                  ..}*@B#@@@;..                  
               .!@@@WkdddddaB@@Z..               
            ..@@@*bdddddddddddh$@@#..            
         .Q@@@*ddddddddddddddddddh@@@$_..        
      .{B@Bbddbkkbdddddddddddddddddddh@@@b..     
   .@@@@hdddddbOzbddddddddddddddddddddddh@@@@.   
   ,Wdddddddddbkkbdddddddddddddddddddddddddd@<   
   !hddddddddddddddddddddddddddddddddddddddd@I   
   .kdddddddddddddda@@@@@@@@@$dddddddddddddd@~   
   :hdddddddddddddda0.......}@dddddwdddddddd@[   
   .adddddddddddddda@@@@@$..@@dddddddddddddd@[   
   .odddddddddddddddh$@@@..@@odddddddddddddd@+   
   .odddddddddddddddb@@Z..@@Mddddddddddddddd@<   
   .oddddddddddddddd$@v..@@Wdddddddddddddddd@+   
   .oddddddddddddddd$<..@@$ddddddddddddddddd@[   
   .odddddddddddddddB@@@@@dddddddddddddddddd@[   
   .*ddddddddddddddddddddddddddddddddddddddd@;   
   :@ddddddddddddddddddddddddddddddddddddddd@-   
   .@@@MhddddddddddddddddddddddddddddddddM@@@.   
     .n@@@Wodddddddddddddddddddddddddh*@@@..     
        ..`@@WhdddddddddddddddddddaW@h!..        
            .~@@$hbdddddddddddda@@@,.            
               ./M@@addddddba$@@].               
                  ..CB@Mk*@#n..                  
                     .."<i..                                       
"""
a4 = r"""
                     ..^....                     
                  ..}*@B#@@@;..                  
               .1@@@WkdddddaB@@n..               
            ."@@@adddddddddddda@@@@..            
         .Q@@$oddddddddddddddddddbB@@@_..        
      .{B@Bbdddkkkdddddddddddddddddddh@@@b..     
   .@@@@hddddddknkddddddddddddddddddddddh@@@@.   
   ,Wddddddddddkkkdddddddddddddddddddddddddd@<   
   !hddddddddddddddddddddddddddddddddddddddd@I   
   .kdddddddddddddddddb@@@@@@ddddddddddddddd@~   
   :hddddddddddddddddo@@w..X@ddddddddddddddd@[   
   .addddddddddddddd@@@....Q@ddddddddddddddd@[   
   .odddddddddddddd@@@..@..@@Bdddddddddddddd@~   
   .odddddddddddddd@..."@...*@dddddddddddddd@)   
   .odddddddddddddd@B.......C@dddddddddddddd@1   
   .oddddddddddddddM@@@@@..o@$dddddddddddddd@]   
   .oddddddddddddddddddo@@@@@ddddddddddddddd@[   
   .*ddddddddddddddddddddddddddddddddddddddd@;   
   :@ddwwwdddddddddddddddddddddddddddddddddd@-   
   .@@@*@wdddddddddddddddddddddddddddddddM@@@.   
     .n@@@Wodddddddddddddddddddddddddk*@@@..     
        ..`@@$adddddddddddddddddddo@@o~..        
            .i@@$hddddddddddddda@@@'.            
               .1@@@addddddba$@@~.               
                  ..CB@Mk*@#n..                  
                     .."<i..                                             
"""
a14 = r"""
                     ..^....                     
                  ..}*@B#@@@;..                  
               .1@@@WkdddddaB@@j..               
            ."@@@addddddddddddo@@@@..            
         .Q@@$oddddddddddddddddddkB@@@_..        
      .{B@Bbdddddddddddddddddddddddddh@@@b..     
   .@@@@hdddddddddddddddddddddddddddddddh@@@@.   
   ,Wddddddddddddddddddddddddddddddddddddddd@<   
   !hddddddddddddddddddddddddddddddddddddddd@I   
   .kdddddddddddd#@@@@@@dd*@@@@@kddddddddddd@~   
   :hdddddddddddd@M...r@d@@@...@#ddddddddddd@[   
   'hdddddddddddd@....n@@@@....@@ddddddddddd@[   
   .hdddddddddddd@@@..h@@0..@..@@odddddddddd@l   
   !hddddddddddddd@@..k@...a-.._@Bdddddddddd@z   
   'hddddddddddddd@@..O@(......'WBdddddddddd@^   
   .addddddddddddd$@..t@@@@@@..@@odddddddddd@;   
   .oddddddddddddda@@@@@ddd@@@@@addddddddddd@[   
   .*ddddddddddddddddddddddddddddddddddddddd@;   
   :@ddddddddddddddddddddddddddddddddddddddd@-   
   .@@@#kdddddddddddddddddddddkddddddddddM@@@.   
     .n@@@Bodddddddddddddddddddddddddk*@@@..     
        ...@@$adddddddddddddddddddo@@o~..        
            .i@@$hbdddddddddddda@@@'.            
               ./M@@addddddba$@@~.               
                  ..CB@Mk*@#n..                  
                     .."<i..                                             
"""
a13 = r"""
                     ..^....                     
                  ..}*@B#@@@;..                  
               .n@@@WkdddddaB@@0..               
            ."@@@hddddddddddddh$@@@..            
         .Q@@$oddddddddddddddddddkB@@@_..        
      .{B@Bbdddddddddddddddddddddddddh@@@b..     
   .@@@@hdddZdddddddddddddddddddddddddddh@@@@.   
   ,Wddddddddddddddddddddddddddddddddddddddd@<   
   !hddddddddddddddddddddddddddddddddddddddd@I   
   .kdddddddddddd#@@@@@@@@@@@@@@dddddddddddd@~   
   :hdddddddddddd@M...r@b.....n@@ddddddddddd@[   
   .adddddddddddd@....x@@@@@@..x@ddddddddddd@[   
   .odddddddddddd@@@..d@$@....@@@ddddddddddd@^   
   .oddddddddddddd@@..m@W@MO<..@@bdddddddddd@>   
   .oddddddddddddd@@..n@@@@@@...@bdddddddddd@i   
   .oddddddddddddd$@..[@.......@@bdddddddddd@]   
   .oddddddddddddda@@@@@@@@@@@@@hddddddddddd@[   
   .*ddddddddddddddddddddbkkbddddddddddddddd@I   
   :@ddddddddddddddddddddddddddddddddddddddd@i   
   .@@@MkddddddddddddddddddddddddddddddddM@@@.   
     .n@@@Wodddddddddddddddddddddddddh*@@@..     
        ...h@@Mhddddddddddddddddddo@@*I..        
            ."Y@$hbdddddddddddda@@@'.            
               ./M@@addddddba$@@~.               
                  ..CB@Mk*@#n..                  
                     .."<i..                                 
"""
a3 = r"""
                     ..^....                     
                  ..}*@B#@@@;..                  
               .!@@@WkdddddaB@@n..               
            ..@@@*bddddddddddda@@@M..            
         .Q@@@*ddddddddddddddddddkB@@@_..        
      .{B@Bbdddddddddddddddddddddddddh@@@b..     
   .@@@@hdddddddddddddddddddddddddddddddh@@@@.   
   ,Wddddddddddddddddddddddddddddddddddddddd@<   
   !hddddddddddddddddddddddddddddddddddddddd@I   
   .kddddddddddddddd@@@@@@@@*ddddddddddddddd@~   
   :hddddddddddddddd@......@@ddddddddddddddd@[   
   .addddddddddddddd@@@@@...@ddddddddwdddddd@[   
   .odddddddddddddddo@>...'@@hdddddddddddddd@]   
   .odddddddddddddddh@@zC..'@Wdddddddddddddd@1   
   .odddddddddddddd*@@@@@@..@Wdddddddddddddd@1   
   .odddddddddddddd*|......@@*dddddddddddddd@]   
   .odddddddddddddd*@@@@@@@@$ddddddddddddddd@[   
   .*dddddddddddddddddbbbbdddddddddddddddddd@;   
   :@ddddddddddddddddddddddddddddddddddddddd@-   
   .@@@MhddddddddddddddddddddddddddddddddM@@@.   
     .n@@@Wodddddddddddddddddddddddddk*@@@..     
        ..`@@$adddddddddddddddddddo@@o~..        
            .i@@$hbdddddddddddda@@@'.            
               ./M@@addddddba$@@~.               
                  ..CB@Mk*@#n..                  
                     .."<i..                                              
"""
a12 = r"""
                     ..^....                     
                  ..}*@B#@@@;..                  
               .!@@@WkdddddaB@@n..               
            ..@@@*bddddddddddda@@@@..            
         .Q@@@*ddddddddddddddddddbB@@@_..        
      .{B@Bbdddddddddddddddddddddddddh@@@b..     
   .@@@@hdddddddddddddddddddddddddddddddh@@@@.   
   ,Wddddddddddddddddddddddddddddddddddddddd@<   
   !hddddddddddddddddddddddddddddddddddddddd@I   
   .kdddddddddddd#@@@@@@@@@@@@@@bddddddddddd@~   
   :hdddddddddddd@M...r@a.....[@@ddddddddddd@[   
   .adddddddddddd@....x@@)@@@...@ddddddddddd@[   
   .odddddddddddd@@@..d@@@@@@..[@ddddddddddd@+   
   .oddddddddddddd@@..m@@@@@..c@@ddddddddddd@~   
   .oddddddddddddd@@..J@@@..B@@@@bdddddddddd@)   
   .oddddddddddddd$@..[@........@bdddddddddd@]   
   .oddddddddddddda@@@@@@@@@@@@@@bdddddddddd@[   
   .*ddddddddddddddddddddbbkbddddddddddddddd@;   
   :@ddwwwdddddddddddddddddddddddddddddddddd@-   
   .@@@*@wddddddddddddddddkddddddddddddddM@@@.   
     .n@@@Wodddddddddddddddddddddddddh*@@@..     
        ..`@@$adddddddddddddddddddhW@aI..        
            .i@@$hddddddddddddda@@$[.            
               .1@@@addddddba$@@].               
                  ..CB@Mk*@#n..                  
                     .."<i..                                    
"""
a5 = r"""
                     ..^....                     
                  ..}*@B#@@@;..                  
               .1@@@WkdddddaB@@n..               
            ."@@@adddddddddddda@@@B..            
         .Q@@$oddddddddddddddddddkW@@W}..        
      .{B@Bbdddkkkdddddddddddddddddddk@@@b..     
   .@@@@hddddddknkddddddddddddddddddddddh@@@@.   
   ,Wddddddddddkkkdddddddddddddddddddddddddd@<   
   !hddddddddddddddddddddddddddddddddddddddd@I   
   .kddddddddddddddd#@@@@@@@@ddddddddddddddd@~   
   :hddddddddddddddd@@......@ddddddddddddddd@[   
   .addddddddddddddd@X.<@@@@@ddddddddddddddd@[   
   .oddddddddddddddd@.....C@@odddddddddddddd@+   
   .oddddddddddddddd@@@@@...@Wdddddddddddddd@<   
   .odddddddddddddd*@@@@@#..@Wdddddddddddddd@[   
   .odddddddddddddd*|......@@odddddddddddddd@[   
   .odddddddddddddd*@@@@@@@@#ddddddddddddddd@[   
   .*dddddddddddddddddbbbbdddddddddddddddddd@;   
   :@ddddddddddddddddddddddddddddddddddddddd@-   
   .@@@MkddddddddddddddddddddddddddddddddM@@@.   
     .n@@@Wodddddddddddddddddddddddddk*@@@..     
        ..`@@Whdddddddddddddddddddo@@o~..        
            .~@@$hbdddddddddddda@@@'.            
               ./M@@addddddba$@@~.               
                  ..CB@Mk*@#n..                  
                     .."<i..                                        
"""
a20 = r"""
                     ..^....                     
                  ..}*@B#@@@;..                  
               .!@@@WkdddddaB@@X..               
            ..@@@*bdddddddddddaB@@@..            
         .Q@@@*ddddddddddddddddddbW@@@_..        
      .{B@Bbdddddddddddddddddddddddddh@@@b..     
   .@@@@hdbkkdddddddddddddddddddddddddddh@@@@.   
   ,WdddddbYmddddddddddddddddddddddddddddddd@<   
   !hdddddbkkddddddddddddddddddddddddddddddd@I   
   .kddddddddddd*@@@@@@@@@@@@@@@hdddwddddddd@~   
   :hdddddddddddBJ.....@@@....;@@kdddddddddd@[   
   .hdddddddddddB@}@@@..Y..@@...@@dddddddddd@[   
   .hddddddddddda@@@@@..I.<@@@..@@dddddddddd@]   
   !hdddddddddddo@@@_..@J.{@@@..@@dddddddddd@1   
   .hddddddddddh@@<..@@@@..@@~..@@dddddddddd@1   
   .oddddddddddh*........0.....@@adddddddddd@1   
   .oddddddddddh@@@@@@@@@@@@@@@@oddddddddddd@]   
   .*dddddddddddddbbkbdddddddddddddddddddddd@;   
   :@ddwwwdddddddddddddddddddddddddddddddddd@-   
   .@@@*@wdddddddddddddddddddddddddddddddM@@@.   
     .n@@@Wodddddddddddddddddddddddddk*@@@..     
        ..`@@Whddddddddddddddddddda$@wl..        
            .1@@$hbddddddddddddh$@@".            
               ./M@@addddddba$@@f.               
                  ..CB@Mk*@#n..                  
                     .."<i..                                      
"""
a11 = r"""
                     ..^....                     
                  ..}*@B#@@@;..                  
               .!@@@WkdddddaB@@X..               
            ..@@@*bdddddddddddaB@@@..            
         .Q@@@*ddddddddddddddddddbB@@@_..        
      .{B@Bbdddddddddddddddddddddddddh@@@b..     
   .@@@@hdddddddddddddddddddddddddddddddh@@@@.   
   ,Wddddddddddddddddddddddddddddddddddddddd@<   
   !hddddddddddddddddddddddddddddddddddddddd@I   
   .kdddddddddddd#@@@@@@a@@@@@@ddddddddddddd@~   
   ,hdddddddddddd@M...r@@@....@hdddddddddddd@[   
   ,hdddddddddddd@....x@@.....@*dddddddddddd@[   
   .kdddddddddddd@@@..d@@@@b..@Wdddddddddddd@+   
   lkddddddddddddd@@..O@d*@l..@Wdddddddddddd@<   
   !kddddddddddddd@@..z@dh@"..@#dddddddddddd@+   
   .addddddddddddd$@..{@db@...@adddddddddddd@[   
   .*ddddddddddddda@@@@@dd@@@@@bdddddddddddd@[   
   .*ddddddddddddddddddddddddddddddddddddddd@;   
   :@ddddddddddddddddddddddddddddddddddddddd@-   
   .@@@#kddddddddddddddddddddddddddddddddM@@@.   
     .n@@@Wodddddddddddddddddddddddddh*@@@..     
        ..`@@$hdddddddddddddddddddaW@h!..        
            .+@@$hbdddddddddddda@@@,.            
               ./M@@addddddba$@@].               
                  ..CB@Mk*@#n..                  
                     .."<i..                                   
"""
a10 = r"""
                     ..^....                     
                  ..}*@B#@@@;..                  
               .n@@@WkdddddaB@@n..               
            ."@@@hdddddddddddda@@@@..            
         .Q@@$oddddddddddddddddddkB@@@_..        
      .{B@Bbdddddddddddddddddddddddddh@@@b..     
   .@@@@hdddddddddddddddddddddddddddddddh@@@@.   
   ,Wddddddddddddddddddddddddddddddddddddddd@<   
   !hddddddddddddddddddddddddddddddddddddddd@I   
   .kdddddddddddd#@@@@@@$@@@@@@@hddddddddddd@~   
   :hdddddddddddd@M...v@@@....;@@kdddddddddd@[   
   .adddddddddddd@....X@@..@@...@@dddddddddd@[   
   .odddddddddddd@@@..#@..<@@@..@@dddddddddd@+   
   .oddddddddddddd@@..*@..{@@@..@@dddddddddd@<   
   .oddddddddddddd@@..0@0..@@~..@@dddddddddd@+   
   .oddddddddddddd$@..|@@c.....@@adddddddddd@[   
   .oddddddddddddda@@@@@@@@@@@@@oddddddddddd@[   
   .*ddddddddddddddddddddddddddddddddddddddd@;   
   :@ddddddddddddddddddddddddddddddddddddddd@-   
   .@@@MhddddddddddddddddddddddddddddddddM@@@.   
     .n@@@Wodddddddddddddddddddddddddh*@@@..     
        ...h@@MhddddddddddddddddddaB@h!..        
            ."C@$hbddddddddddddhW@B^.            
               ./M@@addddddba$@@1.               
                  ..CB@Mk*@#n..                  
                     .."<i..                         
"""
a9 = r"""
                     ..^....                     
                  ..}*@B#@@@;..                  
               .!@@@WkdddddaB@@X..               
            ..@@@*bdddddddddddaB@@M..            
         .Q@@@*ddddddddddddddddddkB@@@_..        
      .{B@Bbdddddddddddddddddddddddddh@@@b..     
   .@@@@hdddddddddddddddddddddddddddddddh@@@@.   
   ,Wddddddddddddddddddddddddddddddddddddddd@<   
   !hddddddddddddddddddddddddddddddddddddddd@I   
   .kdddddddddddddd$@@@@@@@*dddddddddddddddd@~   
   :hddddddddddddd@@@.....@@#ddddddddddddddd@[   
   .addddddddddddd@)..@@h..@@ddddddddddddddd@[   
   .oddddddddddddd@...@@@..k@ddddddddddddddd@^   
   .oddddddddddddd@@^......@@@oddddddddddddd@>   
   .oddddddddddddda@@@@@..$@@@@ddddddddddddd@i   
   .odddddddddddddd@.....@@...@ddddddddddddd@]   
   .odddddddddddddd@@@@@@@@@@@@ddddddddddddd@[   
   .*ddddddddddddddddddddddddddddddddddddddd@;   
   :@ddddddddddddddddddddddddddddddddddddddd@-   
   .@@@MhddddddddddddddddddddddddddddddddM@@@.   
     .n@@@Bodddddddddddddddddddddddddk*@@@..     
        ...@@$adddddddddddddddddddo@@o~..        
            .i@@$hbdddddddddddda@@@'.            
               ./M@@addddddba$@@~.               
                  ..CB@Mk*@#n..                  
                     .."<i..                                        
"""
a8 = r"""
                     ..^....                     
                  ..}*@B#@@@;..                  
               .n@@@WkdddddaB@@n..               
            ."@@@hdddddddddddda@@@@<.            
         .Q@@$odddddddddddddddddddo@@@_..        
      .{B@Bbdddddddddddddddddddddddddh@@@b..     
   .@@@@hdddddddddddddddddddddddddddddddh@@@@.   
   ,Wddddddddddddddddddddddddddddddddddddddd@<   
   !hddddddddddddddddddddddddddddddddddddddd@I   
   .kdddddddddddddddM@@@@@@@@ddddddddddddddd@~   
   :hddddddddddddddo@@.....B@Mdddddddddddddd@[   
   .adddddddddddddd*@..@@@..B$dddddddddddddd@[   
   .odddddddddddddd@@@.....$@@dddddddddddddd@^   
   .odddddddddddddd@@...j...@@dddddddddddddd@>   
   .odddddddddddddd@[..@@@...@dddddddddddddd@i   
   .odddddddddddddd@@-......@@dddddddddddddd@]   
   .oddddddddddddddk@@@@@@@@@kdddddddddddddd@[   
   .*ddddddddddddddddddbbbdddddddddddddddddd@;   
   :@ddddddddddddddddddddddddddddddddddddddd@-   
   .@@@MkdddddddddddddddddddddkddddddddddM@@@.   
     .n@@@Wodddddddddddddddddddddddddk*@@@..     
        ..`@@Whdddddddddddddddddddo@@o~..        
            .~@@$hbdddddddddddda@@@'.            
               ./M@@addddddba$@@~.               
                  ..CB@Mk*@#n..                  
                     .."<i..                                  
"""
a19 = r"""
                     ..^....                     
                  ..}*@B#@@@;..                  
               ._@@@WkdddddaB@@X..               
            ..@@@oddddddddddddaB@@@..            
         .Q@@@oddddddddddddddddddbB@@@_..        
      .{B@Bbdddddddddddddddddddddddddh@@@b..     
   .@@@@hdddddddddddddddddddddddddddddddh@@@@.   
   ,Wddddddwdddddddddddddddddddddddddddddddd@<   
   !hddddddddddddddddddddddddddddddddddddddd@I   
   .kdddddddddddW@@@@@W@@@@@@@@kdddddddddddd@~   
   :hddddddddddk@d...@@@X....n@@bddddddddddd@[   
   .addddddddddkB....@@...@@...@*ddddddddddd@[   
   .oddddddddddk@@@..@@..$@@@..@Wddddddddddd@^   
   .adddddddddddd@@..@@@.......@@@bddddddddd@>   
   !hdddddddddddd@@..@@@@@@@..@@@@@ddddddddd@i   
   .hdddddddddddd@a..@@Q....f@+...@ddddddddd@]   
   .oddddddddddddB@@@@@@@@@@@@@@@@@ddddddddd@[   
   .*ddddddddddddddddddddddddddddddddddddddd@;   
   :@ddddddddddddddddddddddddddddddddddddddd@-   
   .@@@MhddddddddddddddddddddddddddddddddM@@@.   
     .n@@@Wodddddddddddddddddddddddddka@@@..     
        ..`@@$addddddddddddddddddda$@h<`.        
            .i@@$hbdddddddddddda@@@".            
               ./M@@addddddba$@@].               
                  ..CB@Mk*@#n..                  
                     .."<i..                                 
"""